from core.models.email_conversation import (
    EmailConversation,
    STATE_AWAITING_CONFIRMATION,
    STATE_BOOKED,
    STATE_PROPOSING_SLOTS,
    STATE_CLOSED,
    STATE_STORNIERT,
    STATE_DELIVERY_FAILED,
    STATE_DIALOG,
)
from core.models.oauth_state import OAuthState
from core.models.visualisierung import (
    Visualisierung,
    VIZ_STATUS_PENDING,
    VIZ_STATUS_GENERATING,
    VIZ_STATUS_DONE,
    VIZ_STATUS_FAILED,
    VIZ_STATUS_MAIL_QUEUED,
    VIZ_STATUS_SENT,
)
from core.models.beleg import (
    Beleg,
    BELEG_STATUS_PENDING,
    BELEG_STATUS_UPLOADING,
    BELEG_STATUS_UPLOADED,
    BELEG_STATUS_ERROR,
    BELEG_SOURCE_MAIL,
    BELEG_SOURCE_API,
)
from core.models.oauth_token import OAuthToken
from core.models.tenant import Tenant, TenantStatus
from core.models.employee import (
    Employee,
    CALENDAR_PROVIDER_GOOGLE,
    CALENDAR_PROVIDER_MICROSOFT,
    CALENDAR_PROVIDERS,
    SKILL_HEIZUNG,
    SKILL_SANITAER,
    SKILL_ELEKTRIK,
    SKILL_DACH,
    SKILL_TISCHLER,
    SKILL_MALER,
    SKILL_ALLGEMEIN,
    ALLE_SKILLS,
    get_default_employee,
    get_employees_for_tenant,
)
from core.models.health_check import (
    CronHeartbeat,
    HealthCheckResult,
    HEALTH_STATUS_OK,
    HEALTH_STATUS_DEGRADED,
    HEALTH_STATUS_ERROR,
)
from core.models.employee_absence import (
    EmployeeAbsence,
    ABSENCE_KRANK,
    ABSENCE_URLAUB,
    ABSENCE_SONSTIGES,
    ALLE_ABSENCE_TYPES,
    is_employee_absent_on,
    get_active_absences,
    get_upcoming_absences,
    create_absence,
    close_absence,
    is_employee_working_at,
    get_available_employees,
)
from core.models.employee_activation_token import (
    EmployeeActivationToken,
    create_activation_token,
    consume_activation_token,
    consume_activation_code,
    format_short_code,
)
from core.models.tenant_knowledge import (
    TenantKnowledge,
    KATEGORIE_LEISTUNGEN,
    KATEGORIE_MATERIALIEN,
    KATEGORIE_PREISE,
    KATEGORIE_ANFAHRT,
    KATEGORIE_NOTFALL,
    KATEGORIE_OEFFNUNGSZEITEN,
    KATEGORIE_BESONDERHEITEN,
    KATEGORIE_FAQ,
    ALLE_KATEGORIEN,
    KATEGORIE_LABELS,
    QUELLE_MENSCH,
    QUELLE_Q,
    QUELLE_TEMPLATE,
    QUELLE_IMPORT,
    ALLE_QUELLEN,
    QUELLE_LABELS,
    SICHTBARKEIT_KUNDE,
    SICHTBARKEIT_INTERN,
    ALLE_SICHTBARKEITEN,
    SICHTBARKEIT_LABELS,
)
from core.models.wissensluecke import (
    Wissensluecke,
    KANAL_VOICE,
    KANAL_MAIL,
    KANAL_APP,
    ALLE_KANAELE,
    KANAL_LABELS,
    STATUS_OFFEN as LUECKE_STATUS_OFFEN,
    STATUS_BEANTWORTET as LUECKE_STATUS_BEANTWORTET,
    STATUS_VERWORFEN as LUECKE_STATUS_VERWORFEN,
)
from core.models.tenant_kalkulation import (
    TenantKalkulation,
    KALKULATION_SOURCE_MANUAL,
    KALKULATION_SOURCE_Q,
    KALKULATION_SOURCE_TEMPLATE,
)
from core.models.rechnung import (
    Rechnung,
    RECHNUNG_STATUS_EXTRACTING,
    RECHNUNG_STATUS_PREVIEWING,
    RECHNUNG_STATUS_CREATING,
    RECHNUNG_STATUS_DRAFTED,
    RECHNUNG_STATUS_MAIL_QUEUED,
    RECHNUNG_STATUS_MAIL_SENT,
    RECHNUNG_STATUS_BEZAHLT,
    RECHNUNG_STATUS_ERROR,
    RECHNUNG_STATUS_CANCELLED,
    RECHNUNG_INPUT_TEXT,
    RECHNUNG_INPUT_VOICE,
)
from core.models.rechnung_position import RechnungPosition
from core.models.tool_config import ToolConfig
from core.models.automation_setting import AutomationSetting
from core.models.employee_permission import EmployeePermission
from core.models.geocode_cache import GeocodeCache

__all__ = [
    "Tenant",
    "TenantStatus",
    "Employee",
    "CALENDAR_PROVIDER_GOOGLE",
    "CALENDAR_PROVIDER_MICROSOFT",
    "CALENDAR_PROVIDERS",
    "SKILL_HEIZUNG",
    "SKILL_SANITAER",
    "SKILL_ELEKTRIK",
    "SKILL_DACH",
    "SKILL_TISCHLER",
    "SKILL_MALER",
    "SKILL_ALLGEMEIN",
    "ALLE_SKILLS",
    "get_default_employee",
    "get_employees_for_tenant",
    "CronHeartbeat",
    "HealthCheckResult",
    "HEALTH_STATUS_OK",
    "HEALTH_STATUS_DEGRADED",
    "HEALTH_STATUS_ERROR",
    "EmployeeAbsence",
    "ABSENCE_KRANK",
    "ABSENCE_URLAUB",
    "ABSENCE_SONSTIGES",
    "ALLE_ABSENCE_TYPES",
    "is_employee_absent_on",
    "get_active_absences",
    "get_upcoming_absences",
    "create_absence",
    "close_absence",
    "is_employee_working_at",
    "get_available_employees",
    "EmployeeActivationToken",
    "create_activation_token",
    "consume_activation_token",
    "consume_activation_code",
    "format_short_code",
    "TenantKnowledge",
    "KATEGORIE_LEISTUNGEN",
    "KATEGORIE_MATERIALIEN",
    "KATEGORIE_PREISE",
    "KATEGORIE_ANFAHRT",
    "KATEGORIE_NOTFALL",
    "KATEGORIE_OEFFNUNGSZEITEN",
    "KATEGORIE_BESONDERHEITEN",
    "KATEGORIE_FAQ",
    "ALLE_KATEGORIEN",
    "KATEGORIE_LABELS",
    "QUELLE_MENSCH",
    "QUELLE_Q",
    "QUELLE_TEMPLATE",
    "QUELLE_IMPORT",
    "ALLE_QUELLEN",
    "QUELLE_LABELS",
    "SICHTBARKEIT_KUNDE",
    "SICHTBARKEIT_INTERN",
    "ALLE_SICHTBARKEITEN",
    "SICHTBARKEIT_LABELS",
    "Wissensluecke",
    "KANAL_VOICE",
    "KANAL_MAIL",
    "KANAL_APP",
    "ALLE_KANAELE",
    "KANAL_LABELS",
    "LUECKE_STATUS_OFFEN",
    "LUECKE_STATUS_BEANTWORTET",
    "LUECKE_STATUS_VERWORFEN",
    "TenantKalkulation",
    "KALKULATION_SOURCE_MANUAL",
    "KALKULATION_SOURCE_Q",
    "KALKULATION_SOURCE_TEMPLATE",
    "Rechnung",
    "RECHNUNG_STATUS_EXTRACTING",
    "RECHNUNG_STATUS_PREVIEWING",
    "RECHNUNG_STATUS_CREATING",
    "RECHNUNG_STATUS_DRAFTED",
    "RECHNUNG_STATUS_MAIL_QUEUED",
    "RECHNUNG_STATUS_MAIL_SENT",
    "RECHNUNG_STATUS_BEZAHLT",
    "RECHNUNG_STATUS_ERROR",
    "RECHNUNG_STATUS_CANCELLED",
    "RECHNUNG_INPUT_TEXT",
    "RECHNUNG_INPUT_VOICE",
    "RechnungPosition",
    "ToolConfig",
    "AutomationSetting",
    "EmployeePermission",
    "GeocodeCache",
    "OAuthToken",
    "OAuthState",
    "Visualisierung",
    "WebsiteSalt",
    "WebsiteTag",
    "WebsiteVisit",
    "VIZ_STATUS_PENDING",
    "VIZ_STATUS_GENERATING",
    "VIZ_STATUS_DONE",
    "VIZ_STATUS_FAILED",
    "VIZ_STATUS_MAIL_QUEUED",
    "VIZ_STATUS_SENT",
    "Beleg",
    "BELEG_STATUS_PENDING",
    "BELEG_STATUS_UPLOADING",
    "BELEG_STATUS_UPLOADED",
    "BELEG_STATUS_ERROR",
    "BELEG_SOURCE_MAIL",
    "BELEG_SOURCE_API",
    "EmailConversation",
    "STATE_AWAITING_CONFIRMATION",
    "STATE_BOOKED",
    "STATE_PROPOSING_SLOTS",
    "STATE_CLOSED",
    "STATE_STORNIERT",
    "STATE_DELIVERY_FAILED",
    "STATE_DIALOG",
    "AngebotPosition",
    "AuftragStunden",
    "STUNDEN_MIN",
    "STUNDEN_MAX",
    "Kundengespraech",
    "GespraechDatei",
    "GESPRAECH_DATEI_FOTO",
    "GESPRAECH_DATEI_VISUALISIERUNG",
    "TenantKundeDrive",
    "Kunde",
    "KundeExternalRef",
    "REF_SYSTEM_LEXWARE",
    "Rueckruf",
    "RUECKRUF_STATUS_OFFEN",
    "RUECKRUF_STATUS_ERLEDIGT",
    "RUECKRUF_STATUS_VALID",
    "RUECKRUF_STATUS_LABEL",
    "AppSession",
    "AppLoginToken",
    "AppUsageEvent",
    "record_app_usage",
    "usage_counts_by_employee",
    "USAGE_LOGIN",
    "USAGE_ASSISTENT_BEFEHL",
    "USAGE_ASSISTENT_AKTION",
    "USAGE_DIKTAT",
    "PushSubscription",
    "APP_SESSION_LIFETIME",
    "APP_LOGIN_TOKEN_LIFETIME",
]
from core.models.tenant_leistung import TenantLeistung
from core.models.angebot import (
    Angebot,
    ANGEBOT_STATUS_ERSTELLT,
    ANGEBOT_STATUS_IN_LEXWARE,
    ANGEBOT_STATUS_MAIL_QUEUED,
    ANGEBOT_STATUS_MAIL_SENT,
    ANGEBOT_STATUS_MAIL_FAILED,
    ANGEBOT_STATUS_ACCEPTED,
    ANGEBOT_STATUS_REJECTED,
    ANGEBOT_STATUS_RECHNUNG_ERSTELLT,
)
from core.models.angebot_position import AngebotPosition
from core.models.auftrag_prozess import (
    AuftragProzessSchritt,
    AuftragSchrittStatus,
    MAX_EIGENE_SCHRITTE,
    MAX_SCHRITT_LABEL,
)
from core.models.auftrag_stunden import (
    AuftragStunden,
    STUNDEN_MAX,
    STUNDEN_MIN,
)
from core.models.kundengespraech import Kundengespraech
from core.models.gespraech_datei import (
    GespraechDatei,
    GESPRAECH_DATEI_FOTO,
    GESPRAECH_DATEI_VISUALISIERUNG,
)
from core.models.anfrage import (
    AnfrageToken,
    AnfrageResponse,
    ANFRAGE_TYP_TISCHLER,
    ANFRAGE_TYP_ALLGEMEIN,
    FORMULAR_STATUS_NEU,
    FORMULAR_STATUS_IN_BEARBEITUNG,
    FORMULAR_STATUS_ERLEDIGT,
    FORMULAR_STATUS_ABGELEHNT,
    FORMULAR_STATUS_OFFEN,
    FORMULAR_STATUS_VALID,
    FORMULAR_STATUS_LABEL,
)
from core.models.rueckruf import (
    Rueckruf,
    RUECKRUF_STATUS_OFFEN,
    RUECKRUF_STATUS_ERLEDIGT,
    RUECKRUF_STATUS_VALID,
    RUECKRUF_STATUS_LABEL,
)
from core.models.tenant_anfrage_schema import TenantAnfrageSchema
from core.models.admin import (
    AdminUser,
    AdminSession,
    AdminAuditLog,
    AdminLoginAttempt,
    ApiPricingConfig,
    ApiUsageLog,
    UNIT_INPUT_TOKEN,
    UNIT_OUTPUT_TOKEN,
    UNIT_CACHED_INPUT_TOKEN,
    UNIT_CHARACTER,
    UNIT_SECOND,
    UNIT_REQUEST,
    UNIT_MAIL_SEND,
    PROVIDER_GEMINI,
    PROVIDER_VERTEX,
    PROVIDER_ELEVENLABS,
    PROVIDER_DEEPGRAM,
    PROVIDER_SIPGATE,
    PROVIDER_MICROSOFT,
    PROVIDER_BREVO,
    PROVIDER_LEXWARE,
)
from core.models.tenant_material import (
    TenantMaterial,
    MaterialBestellung,
    BESTELL_ART_LINK,
    BESTELL_ART_MANUAL,
)
from core.models.tenant_kunde_drive import TenantKundeDrive
from core.models.kunde import Kunde
from core.models.kunde_external_ref import KundeExternalRef, REF_SYSTEM_LEXWARE
from core.models.app_account import (
    AppSession,
    AppLoginToken,
    PushSubscription,
    APP_SESSION_LIFETIME,
    APP_LOGIN_TOKEN_LIFETIME,
)
from core.models.app_usage_event import (
    AppUsageEvent,
    record_app_usage,
    usage_counts_by_employee,
    USAGE_LOGIN,
    USAGE_ASSISTENT_BEFEHL,
    USAGE_ASSISTENT_AKTION,
    USAGE_DIKTAT,
)
from core.models.failed_mail_queue import (
    FailedMailQueue,
    FAILED_MAIL_PENDING,
    FAILED_MAIL_SENT,
    FAILED_MAIL_DEAD,
    MAIL_TYPE_RECHNUNG,
    MAIL_TYPE_VISUALISIERUNG,
    MAIL_TYPE_ANGEBOT,
    MAIL_TYPE_REPLY,
    RETRY_BACKOFF_SECONDS,
    MAX_ATTEMPTS,
)

# Besucherzaehlung der Marketing-Website (cookielos, siehe Modul-Docstring).
from core.models.website_visit import (  # noqa: E402
    WebsiteSalt,
    WebsiteTag,
    WebsiteVisit,
    ART_AUFRUF,
    ART_KONTAKT,
    ALLE_ARTEN,
)
